spring:
  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/pokemon
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_query_cache: true
          use_second_level_cache: true
          redisson_config: redisson.yaml
          redisson:
            pokemon:
              expiration:
                time_to_live: 12000
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          provider_class: org.ehcache.jsr107.EhcacheCachingProvider
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
server:
  servlet:
    context-path: /api