spring:
  application:
    name: pokemon-type-service
  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/pokemon_type
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
server:
  servlet:
    context-path: /api
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/