spring:
  application:
    name: user-service
  datasource:
    username: root
    password: 12341234
    url: jdbc:mysql://localhost:3306/user
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
server:
  servlet:
    context-path: /api/user-service
  port: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/